<?php 

$time_zones = [
    [ "offset" => "-39600", "name" => "Midway Island" ],
    [ "offset" => "-39600", "name" => "Samoa" ],
    [ "offset" => "-36000", "name" => "Hawaii" ],
    [ "offset" => "-32400", "name" => "Alaska" ],
    [ "offset" => "-28800", "name" => "Tijuana" ],
    [ "offset" => "-28800", "name" => "Pacific Time (US &amp; Canada)" ],
    [ "offset" => "-25200", "name" => "Mazatlan" ],
    [ "offset" => "-25200", "name" => "Mountain Time (US &amp; Canada)" ],
    [ "offset" => "-25200", "name" => "Arizona" ],
    [ "offset" => "-25200", "name" => "Chihuahua" ],
    [ "offset" => "-21600", "name" => "Central Time (US &amp; Canada)" ],
    [ "offset" => "-21600", "name" => "Mexico City" ],
    [ "offset" => "-21600", "name" => "Central America" ],
    [ "offset" => "-21600", "name" => "Monterrey" ],
    [ "offset" => "-21600", "name" => "Saskatchewan" ],
    [ "offset" => "-18000", "name" => "Eastern Time (US &amp; Canada)" ],
    [ "offset" => "-18000", "name" => "Quito" ],
    [ "offset" => "-18000", "name" => "Indiana (East)" ],
    [ "offset" => "-18000", "name" => "Bogota" ],
    [ "offset" => "-16200", "name" => "Caracas" ],
    [ "offset" => "-14400", "name" => "Georgetown" ],
    [ "offset" => "-14400", "name" => "La Paz" ],
    [ "offset" => "-14400", "name" => "Atlantic Time (Canada)" ],
    [ "offset" => "-12600", "name" => "Newfoundland" ],
    [ "offset" => "-10800", "name" => "Santiago" ],
    [ "offset" => "-10800", "name" => "Buenos Aires" ],
    [ "offset" => "-10800", "name" => "Greenland" ],
    [ "offset" => "-7200", "name" => "Mid-Atlantic" ],
    [ "offset" => "-7200", "name" => "Brasilia" ],
    [ "offset" => "-3600", "name" => "Cape Verde Is." ],
    [ "offset" => "-3600", "name" => "Azores" ],
    [ "offset" => "0", "name" => "London" ],
    [ "offset" => "0", "name" => "Monrovia" ],
    [ "offset" => "0", "name" => "Dublin" ],
    [ "offset" => "0", "name" => "UTC" ],
    [ "offset" => "0", "name" => "Lisbon" ],
    [ "offset" => "0", "name" => "Casablanca" ],
    [ "offset" => "3600", "name" => "Ljubljana" ],
    [ "offset" => "3600", "name" => "Zagreb" ],
    [ "offset" => "3600", "name" => "Budapest" ],
    [ "offset" => "3600", "name" => "Skopje" ],
    [ "offset" => "3600", "name" => "Vienna" ],
    [ "offset" => "3600", "name" => "Prague" ],
    [ "offset" => "3600", "name" => "Bern" ],
    [ "offset" => "3600", "name" => "Amsterdam" ],
    [ "offset" => "3600", "name" => "Sarajevo" ],
    [ "offset" => "3600", "name" => "Stockholm" ],
    [ "offset" => "3600", "name" => "Brussels" ],
    [ "offset" => "3600", "name" => "Bratislava" ],
    [ "offset" => "3600", "name" => "Belgrade" ],
    [ "offset" => "3600", "name" => "Rome" ],
    [ "offset" => "3600", "name" => "Warsaw" ],
    [ "offset" => "3600", "name" => "Paris" ],
    [ "offset" => "3600", "name" => "West Central Africa" ],
    [ "offset" => "3600", "name" => "Madrid" ],
    [ "offset" => "3600", "name" => "Copenhagen" ],
    [ "offset" => "7200", "name" => "Kyiv" ],
    [ "offset" => "7200", "name" => "Athens" ],
    [ "offset" => "7200", "name" => "Pretoria" ],
    [ "offset" => "7200", "name" => "Jerusalem" ],
    [ "offset" => "7200", "name" => "Vilnius" ],
    [ "offset" => "7200", "name" => "Bucharest" ],
    [ "offset" => "7200", "name" => "Helsinki" ],
    [ "offset" => "7200", "name" => "Sofia" ],
    [ "offset" => "7200", "name" => "Cairo" ],
    [ "offset" => "7200", "name" => "Riga" ],
    [ "offset" => "7200", "name" => "Harare" ],
    [ "offset" => "7200", "name" => "Istanbul" ],
    [ "offset" => "7200", "name" => "Tallinn" ],
    [ "offset" => "10800", "name" => "Nairobi" ],
    [ "offset" => "10800", "name" => "Riyadh" ],
    [ "offset" => "10800", "name" => "Kuwait" ],
    [ "offset" => "10800", "name" => "Baghdad" ],
    [ "offset" => "10800", "name" => "Minsk" ],
    [ "offset" => "12600", "name" => "Tehran" ],
    [ "offset" => "14400", "name" => "Baku" ],
    [ "offset" => "14400", "name" => "Yerevan" ],
    [ "offset" => "14400", "name" => "Muscat" ],
    [ "offset" => "14400", "name" => "Tbilisi" ],
    [ "offset" => "14400", "name" => "Volgograd" ],
    [ "offset" => "16200", "name" => "Kabul" ],
    [ "offset" => "18000", "name" => "Karachi" ],
    [ "offset" => "18000", "name" => "Tashkent" ],
    [ "offset" => "19800", "name" => "New Delhi" ],
    [ "offset" => "19800", "name" => "Sri Jayawardenepura" ],
    [ "offset" => "20700", "name" => "Kathmandu" ],
    [ "offset" => "21600", "name" => "Almaty" ],
    [ "offset" => "21600", "name" => "Ekaterinburg" ],
    [ "offset" => "21600", "name" => "Dhaka" ],
    [ "offset" => "23400", "name" => "Rangoon" ],
    [ "offset" => "25200", "name" => "Jakarta" ],
    [ "offset" => "25200", "name" => "Hanoi" ],
    [ "offset" => "25200", "name" => "Novosibirsk" ],
    [ "offset" => "28800", "name" => "Urumqi" ],
    [ "offset" => "28800", "name" => "Ulaan Bataar" ],
    [ "offset" => "28800", "name" => "Hong Kong" ],
    [ "offset" => "28800", "name" => "Perth" ],
    [ "offset" => "28800", "name" => "Beijing" ],
    [ "offset" => "28800", "name" => "Taipei" ],
    [ "offset" => "28800", "name" => "Kuala Lumpur" ],
    [ "offset" => "28800", "name" => "Singapore" ],
    [ "offset" => "28800", "name" => "Krasnoyarsk" ],
    [ "offset" => "28800", "name" => "Chongqing" ],
    [ "offset" => "32400", "name" => "Seoul" ],
    [ "offset" => "32400", "name" => "Irkutsk" ],
    [ "offset" => "32400", "name" => "Tokyo" ],
    [ "offset" => "34200", "name" => "Darwin" ],
    [ "offset" => "36000", "name" => "Yakutsk" ],
    [ "offset" => "36000", "name" => "Port Moresby" ],
    [ "offset" => "36000", "name" => "Brisbane" ],
    [ "offset" => "36000", "name" => "Guam" ],
    [ "offset" => "37800", "name" => "Adelaide" ],
    [ "offset" => "39600", "name" => "Solomon Is." ],
    [ "offset" => "39600", "name" => "New Caledonia" ],
    [ "offset" => "39600", "name" => "Hobart" ],
    [ "offset" => "39600", "name" => "Sydney" ],
    [ "offset" => "39600", "name" => "Melbourne" ],
    [ "offset" => "43200", "name" => "Magadan" ],
    [ "offset" => "43200", "name" => "Kamchatka" ],
    [ "offset" => "43200", "name" => "Marshall Is." ],
    [ "offset" => "46800", "name" => "Fiji" ],
    [ "offset" => "46800", "name" => "Wellington" ],
    [ "offset" => "46800", "name" => "Nuku&#39;alofa" ]
];
